### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by talentbeyondboundaries** [Talent-Catalog/talentcatalog#2]
Unfortunately the original code base was delivered with no unit testing. This is a real shortcoming - especially now that we have moved the code into open source. 

This is another great first issue for newcomers. One of the best ways to understand code is to write unit tests for it. At the same time you are adding real value to the code base.

**Comment by camerojo** [comment]
- [x] Unit test Angular
- [ ] Unit test Spring
