### ISSUE TITLE
Enable ALP Access Logs

### ISSUE THREAD

**Issue by sadatmalik** [Talent-Catalog/talentcatalog#78]
Test it out on staging first

**Comment by sadatmalik** [comment]
Suggested by AWS support - helps them with trouble shooting 

See:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html

**Comment by samschlicht** [comment]
The doc seems fairly clear so I'm going to dive in first, for obvious reasons taking staging first. Will create new buckets for clarity's sake. See that our load balancers are located in the US East Coast, so the buckets have to be same.
- [x] AWS test
- [x] AWS prod

**Comment by samschlicht** [comment]
Noting that if anyone has to do this or something like it again, the Amazon Account ID used in the permissions policy should NOT have the hyphens in it, as the example in the doc suggests. There's potentially a frustrated half hour of your life preempted — you're welcome!

**Comment by samschlicht** [comment]
New buckets created for their respective accounts:
tctalent-test-elb-access-logs
tctalent-prod-elb-access-logs

Respective ELBs both linked and logging in those buckets.
